### ISSUE TITLE
影片對應

### ISSUE THREAD

**Issue by georgefs** [livingbio/elta_spider#2]

**Comment by yun1113** [comment]
| name | video_name | fifa_url | time |
| --- | --- | --- | --- |
| GroupD_CostaRica_England | 128054_3500K_384K_1920x1080_00-00-01_8934_SH14052001-038.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186484/live-blog.html | 1st_start:31:03 1st_end:1:16:15 2nd_start:1:34:05 2nd_end:2:22:15 |
| GroupD_Italy_Uruguay | 128059_3500K_384K_1920x1080_00-00-01_9213_SH14052001-039.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186465/live-blog.html | 1st_start:31:05 1st_end:1:18:14 2nd_start:1:34:45 2nd_end:2:25:40 |
| GroupC_Japan_Colombia | 128065_3500K_384K_1920x1080_00-00-01_9114_SH14052001-040.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186457/live-blog.html | 1st_start:31:05 1st_end:1:17:15 2nd_start:1:35:20 2nd_end:2:23:34 |
| GroupC_Greece_IvoryCoast | 128071_3500K_384K_1920x1080_00-00-01_9118_SH14052001-041.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186455/live-blog.html | 1st_start:31:05 1st_end:1:20:10 2nd_start:1:35:16 2nd_end:2:24:05 |
| GroupF_Nigeria_Argentina | 128089_3500K_384K_1920x1080_00-00-01_9078_SH14052001-042.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186458/live-blog.html | 1st_start:31:04 1st_end:1:18:11 2nd_start:1:35:27 2nd_end:2:24:23 |
| GroupF_BosniaAndHerzegovina_Iran | 128110_3500K_384K_1920x1080_00-00-01_9003_SH14052001-043.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186464/live-blog.html | 1st_start:31:03 1st_end:1:19:03 2nd_start:1:34:46 2nd_end:2:22:47 |
| GroupE_France_Ecuador | 128139_3500K_384K_1920x1080_00-00-01_9084_SH14052001-044.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186515/live-blog.html | 1st_start:31:05 1st_end:1:18:05 2nd_start:1:34:13 2nd_end:2:23:20 |
| GroupE_Honduras_Switzerland | 128195_3500K_384K_1920x1080_00-00-01_8975_SH14052001-045.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186482/live-blog.html | 1st_start:31:08 1st_end:1:18:08 2nd_start:1:34:16 2nd_end:2:22:10 |
| GroupG_Portugal_Ghana | 128565_3500K_384K_1920x1080_00-00-01_9088_SH14052001-047.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186476/live-blog.html | 1st_start:31:03 1st_end:1:16:59 2nd_start:1:33:57 2nd_end:2:24:00 |
| GroupH_Algeria_Russia | 128608_3500K_384K_1920x1080_00-00-01_9004_SH14052001-048.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186506/live-blog.html | 1st_start:31:13 1st_end:1:17:14 2nd_start:1:33:33 2nd_end:2:22:36 |
| ThirdPlace_Brazil_Netherlands | 128638_3500K_384K_1920x1080_00-00-01_10060_SH14052001-064.mp4 | http://www.fifa.com/worldcup/matches/round=255957/match=300186502/live-blog.html | 1st_start:31:11 1st_end:1:18:15 2nd_start:1:34:00 2nd_end:2:24:15 |
| Final_Germany_Argenrina | 128848_3500K_384K_1920x1080_00-00-01_14511_SH14052001-068.mp4 | http://www.fifa.com/worldcup/matches/round=255959/match=300186501/live-blog.html | 1st_start:31:08 1st_end:1:18:10 2nd_start:1:35:23 2nd_end:2:23:13 3ird_start:2:29:41 3ird_end:3:07:00 |
| GroupE_Switzerland_France | 145016_3500K_384K_1920x1080_00-00-01_8957_SH14052001-026.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186514/live-blog.html | 1st_start:31:07 1st_end:1:18:10 2nd_start:1:34:03 2nd_end:2:22:06 |
| GroupG_Germany_Ghana | 145018_3500K_384K_1920x1080_00-00-01_9014_SH14052001-029.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186493/live-blog.html | 1st_start:31:09 1st_end:1:17:19 2nd_start:1:33:59 2nd_end:2:23:03 |
| GroupD_Urugury_CostaRica | 145022_3500K_384K_1920x1080_00-00-01_9199_SH14052001-007.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186489/live-blog.html | 1st_start:32:12 1st_end:1:19:12 2nd_start:1:35:43 2nd_end:2:25:44 |

| name | video_name | fifa_url | time |
| --- | --- | --- | --- |
| 開幕式 | 124606_3500K_384K_0dB_SH14052001-001.mp4 |  |  |
| GroupA_Brazil_Croatia | 124610_3500K_384K_0dB_SH14052001-002.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186456/live-blog.html | 1st_start:32:55 1st_end:80:04 2nd_start:96:00 2nd_end:145:45 |
| GroupA_Mexico_Cameroon | 124622_3500K_384K_0dB_SH14052001-003.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186492/live-blog.html | 1st_start:32:29 1st_end:79:31 2nd_start:97:20 2nd_end:146:28 |
| GroupB_Spain_Netherlands | 124634_3500K_384K_0dB_SH14052001-004.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186510/live-blog.html | 1st_start:31:41 1st_end:77:54 2nd_start:93:37 2nd_end:142:20 |
| GroupB_Chile_Australia | 124646_3500K_384K_0dB_SH14052001-005.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186473/live-blog.html | 1st_start:31:09 1st_end:77:37 2nd_start:93:48 2nd_end:142:49 |
| GroupF_Iran_Nigeria | 124722_3500K_384K_0dB_SH14052001-014.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186505/live-blog.html | 1st_start:31:17 1st_end:78:21 2nd_start:94:44 2nd_end:141:45 |
| GroupG_Ghana_USA | 124725_3500K_384K_0dB_SH14052001-015.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186512/live-blog.html | 1st_start:31:28 1st_end:81:27 2nd_start:97:22 2nd_end:147:02 |
| GroupD_England_Italy | 124837_3500K_384K_0dB_SH14052001-008.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186513/live-blog.html | 1st_start:31:08 1st_end:78:21 2nd_start:94:52 2nd_end:144:58 |
| GroupE_Switzerland_Ecuador | 124842_3500K_384K_0dB_SH14052001-010.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186494/live-blog.html | 1st_start:31:03 1st_end:77:35 2nd_start:92:38 2nd_end:141:29 |
| GroupC_Colombia_Greece | 124895_3500K_384K_0dB_SH14052001-006.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186471/live-blog.html | 1st_start:32:05 1st_end:78:08 2nd_start:94:42 2nd_end:141:31 |
| GroupE_France_Honduras | 124907_3500K_384K_0dB_SH14052001-011.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186496/live-blog.html | 1st_start:30:47 1st_end:79:26 2nd_start:94:47 2nd_end:142:50 |
| GroupF_Argentina_BosniaAndHerzegovina | 124928_3500K_384K_0dB_SH14052001-012.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186477/live-blog.html | 1st_start:31:35 1st_end:77:49 2nd_start:94:00 2nd_end:142:04 |
| GroupG_Germany_Portugal | 124929_3500K_384K_0dB_SH14052001-013.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186475/live-blog.html | 1st_start:31:02 1st_end:78:06 2nd_start:95:31 2nd_end:142:32 |
| GroupA_Brazil_Mexico | 124938_3500K_384K_0dB_SH14052001-017.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186509/live-blog.html | 1st_start:31:21 1st_end:77:19 2nd_start:93:15 2nd_end:141:17 |
| GroupH_Belgium_Russia | 124972_3500K_384K_0dB_SH14052001-031.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186481/live-blog.html | 1st_start:30:59 1st_end:77:07 2nd_start:93:28 2nd_end:141:50 |
| GroupH_KoreaRepublic_Algeria | 125037_3500K_384K_0dB_SH14052001-032.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186495/live-blog.html | 1st_start:31:10 1st_end:78:09 2nd_start:93:28 2nd_end:142:33 |
| GroupG_USA_Portugal | 125047_3500K_384K_0dB_SH14052001-033.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186483/live-blog.html | 1st_start:31:10 1st_end:78:15 2nd_start:94:16 2nd_end:144:44 |
| GroupE_Honduras_Ecuador | 125274_3500K_384K_0dB_SH14052001-027.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186463/live-blog.html | 1st_start:31:32 1st_end:79:34 2nd_start:94:44 2nd_end:144:07 |
| GroupF_Argentina_Iran | 125283_3500K_384K_0dB_SH14052001-028.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186466/live-blog.html | 1st_start:31:14 1st_end:78:17 2nd_start:94:35 2nd_end:144:09 |
| GroupF_Nigeria_BosniaAndHerzegovina | 125297_3500K_384K_0dB_SH14052001-030.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186511/live-blog.html | 1st_start:31:07 1st_end:77:15 2nd_start:92:16 2nd_end:140:27 |
| GroupH_Russia_KoreaRepublic | 125336_3500K_384K_0dB_SH14052001-018.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186499/live-blog.html | 1st_start:31:07 1st_end:77:11 2nd_start:92:12 2nd_end:141:12 |
| GroupB_Spain_Chile | 126123_3500K_384K_0dB_SH14052001-020.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186498/live-blog.html | 1st_start:31:35 1st_end:78:50 2nd_start:95:28 2nd_end:146:30 |
| GroupA_Cameroon_Croatia | 126393_3500K_384K_0dB_SH14052001-021.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186453/live-blog.html | 1st_start:31:11 1st_end:77:17 2nd_start:93:25 2nd_end:140:30 |
| GroupC_Colombia_CoteDivoire | 126401_3500K_384K_0dB_SH14052001-022.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186468/live-blog.html | 1st_start:32:58 1st_end:79:20 2nd_start:96:25 2nd_end:145:44 |
| GroupD_Uruguay_England | 126402_3500K_384K_0dB_SH14052001-023.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186486/live-blog.html | 1st_start:31:08 1st_end:77:07 2nd_start:92:22 2nd_end:142:27 |
| GroupD_Italy_CostaRica | 126404_3500K_384K_0dB_SH14052001-025.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186500/live-blog.html | 1st_start:32:05 1st_end:1:19:17 2nd_start:1:35:29 2nd_end:2:24:10 |
| Round16_Brazil_Chile | 126405_3500K_384K_0dB_SH14052001-050.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186487/live-blog.html | 1st_start:32:22 1st_end:1:19:24 2nd_start:1:36:30 2nd_end:2:24:36 3ird_start:2:32:39 3ird_end:3:09:52 pk_start:3:18:10 pk_end:3:27:04 |
| Round16_Colombia_Uruguay | 126406_3500K_384K_0dB_SH14052001-051.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186491/live-blog.html | 1st_start:31:38 1st_end:1:17:40 2nd_start:1:34:11 2nd_end:2:22:14 |
| Round16_Netherlands_Mexico | 126407_3500K_384K_0dB_SH14052001-052.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186508/live-blog.html | 1st_start:31:05 1st_end:1:26:36 2nd_start:1:36:10 2nd_end:2:27:37 |
| Round16_CostaRica_Greece | 126408_3500K_384K_0dB_SH14052001-053.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186459/live-blog.html | 1st_start:31:42 1st_end:1:18:48 2nd_start:1:36:11 2nd_end:2:26:35 3ird_start:2:35:08  3ird_end:3:09:54 pk_start:3:19:05 pk_end:3:26:22 |
| Round16_France_Nigeria | 126427_3500K_384K_0dB_SH14052001-054.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186462/live-blog.html | 1st_start:31:03 1st_end:1:18:22 2nd_start:1:33:30 2nd_end:2:23:34 |
| Round16_Germany_Algeria | 126538_3500K_384K_0dB_SH14052001-055.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186460/live-blog.html | 1st_start:31:07 1st_end:1:17:11 2nd_start:1:32:28 2nd_end:2:21:26 3ird_start:2:27:33  3ird_end:3:03:12 |
| Round16_Argentina_Switzerland | 126549_3500K_384K_0dB_SH14052001-056.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186503/live-blog.html | 1st_start:30:55 1st_end:1:16:03 2nd_start:1:31:36 2nd_end:2:19:37 3ird_start:2:25:15  3ird_end:3:05:16 |
| Round16_Belgium_USA | 126550_3500K_384K_0dB_SH14052001-057.mp4 | http://www.fifa.com/worldcup/matches/round=255951/match=300186497/live-blog.html | 1st_start:31:10 1st_end:1:19:13 2nd_start:1:34:19 2nd_end:2:22:24 3ird_start:2:28:15  3ird_end:3:02:53 |
| Quarter_Argentina_Belgium | 126556_3500K_384K_0dB_SH14052001-060.mp4 | http://www.fifa.com/worldcup/matches/round=255953/match=300186504/live-blog.html | 1st_start:31:22 1st_end:1:18:24 2nd_start:1:33:58 2nd_end:2:24:00 |
| Quarter_France_Germany | 126608_3500K_384K_0dB_SH14052001-058.mp4 | http://www.fifa.com/worldcup/matches/round=255953/match=300186485/live-blog.html | 1st_start:33:54 1st_end:1:19:49 2nd_start:1:35:51 2nd_end:2:25:25 |
| Quarter_Brazil_Colombia | 126619_3500K_384K_0dB_SH14052001-059.mp4 | http://www.fifa.com/worldcup/matches/round=255953/match=300186461/live-blog.html | 1st_start:32:55 1st_end:1:18:59  2nd_start:1:35:35 2nd_end:2:25:37 |
| Semi_Brazil_Germany | 126625_3500K_384K_0dB_SH14052001-062.mp4 | http://www.fifa.com/worldcup/matches/round=255955/match=300186474/live-blog.html | 1st_start:31:09 1st_end:1:17:10  2nd_start:1:32:13 2nd_end:2:19:07 |
| Semi_Netherlands_Argentina | 126635_3500K_384K_0dB_SH14052001-063.mp4 | http://www.fifa.com/worldcup/matches/round=255955/match=300186490/live-blog.html | 1st_start:31:59 1st_end:1:19:03  2nd_start:1:35:31 2nd_end:2:23:37 3ird_start:2:30:14 3ird_end:3:04:15 pk_start:3:09:40 pk_end:3:16:10 |
| GroupB_Australia_Spain | 127956_3500K_384K_0dB_SH14052001-034.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186467/live-blog.html | 1st_start:31:02 1st_end:1:16:35 2nd_start:1:33:45 2nd_end:2:21:46 |
| GroupB_Netherlands_Chile | 127967_3500K_384K_0dB_SH14052001-035.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186470/live-blog.html | 1st_start:31:06 1st_end:1:17:10 2nd_start:1:33:57 2nd_end:2:22:03 |
| GroupA_Cameroon_Brazil | 127972_3500K_384K_0dB_SH14052001-036.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186472/live-blog.html | 1st_start:31:12 1st_end:1:17:20 2nd_start:1:34:49 2nd_end:2:23:52 |
| GroupA_Croatia_Mexico | 128047_3500K_384K_0dB_SH14052001-037.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186452/live-blog.html | 1st_start:31:10 1st_end:1:18:38 2nd_start:1:34:29 2nd_end:2:23:30 |
| GroupD_CoataRica_England | 128054_3500K_384K_0dB_SH14052001-038.mp4 | http://www.fifa.com/worldcup/matches/round=255931/match=300186484/live-blog.html | 1st_start:31:06 1st_end:1:16:15 2nd_start:1:34:08 2nd_end:2:22:13 |

Folder: 2014_世界盃

**Comment by yun1113** [comment]
| name | video_name | fifa_url | time |
| --- | --- | --- | --- |
| ThiedPlace_Belgium_Mexico | 145022_3500K_384K_1920x1080_00-00-01_9199_SH14052001-007.mp4 | http://www.fifa.com/u17worldcup/matches/round=271775/match=300298409/index.html | 1st_start:16:08 1st_end:63:19 2nd_start:78:23 2nd_end:128:20 |

Folder: 2015_U17

**Comment by yun1113** [comment]
| name | video_name | fifa_url | time |
| --- | --- | --- | --- |
| ThirdPlace_Uruguay_Germany | 159147_3500K_384K_1920x1080_00-00-01_9510_10M-2010FIFA_0711烏拉圭VS德國.mp4 | http://www.fifa.com/worldcup/matches/round=249721/match=300061509/live-blog.html | 1st_start:31:27 1st_end:77:26 2nd_start:93:18 2nd_end:141:17 |
| Final_Netherlands_Spain | 159159_3500K_384K_1920x1080_00-00-01_14847_10M-2010FIFA_0712荷蘭VS西班牙.mp4 | http://www.fifa.com/worldcup/matches/round=249721/match=300061509/live-blog.html | 1st_start:1:00:07 1st_end:1:47:22 2nd_start:2:02:24 2nd_end:2:50:32 3ird_start:2:55:46 3ird_end:3:32:12 |

Folder: 2010世界盃

**Comment by yun1113** [comment]
| name | video_name | fifa_url | time |
| --- | --- | --- | --- |
| SemiFinal_Germany_France | 172975_3500K_384K_1920x1080_00-00-01_9183_SH16052911-050.mp4 | http://www.fifa.com/live-scores/uefaeuro/matches/match=Germany-France-300361557/index.html | 1st_start:31:57 1st_end:78:40 2nd_start:94:43 2nd_end:144:05 |
| Final_Portugal_France | 172978_3500K_384K_1920x1080_00-00-01_12637_SH16052911-051.mp4 | http://www.fifa.com/live-scores/uefaeuro/matches/match=Portugal-France-300362364/index.html | 1st_start:32:04 1st_end:79:49 2nd_start:94:57 2nd_end:142:59 3rd_start:148:23 3rd_end:183:22 |

Folder: 2016歐洲盃

**Comment by yun1113** [comment]
| name | video_name | fifa_url | 時間 |
| --- | --- | --- | --- |
| GroupD_Japan_Honduras | 49371_3500K_384K_1920x1080_00-00-01_7500_40M_2012倫敦奧運-CH04_0801_2350_足球_男子預賽_日本vs宏都拉斯_1.mp4 | http://www.fifa.com/mensolympic/matches/round=256009/match=300197690/index.html#lineups | 1st_start:8:48 1st_end:54:50 2nd_start:71:04 2nd_end:120:03 |
| QuarterFinals_Japan_Egypt | 49394_3500K_384K_1920x1080_00-00-01_7522_40M_2012倫敦奧運-CH04_0804_1850_足球_男子_半準決賽_日本VS埃及_1.mp4 | http://www.fifa.com/mensolympic/matches/round=256021/match=300197694/index.html#lineups | 1st_start:9:48 1st_end:56:52 2nd_start:72:05 2nd_end:120:12 |

Folder: 2012_奧運足球

**Comment by lucemia** [comment]
2014 世界杯 GroupD_CostaRica_England 出現了兩次
