### ISSUE TITLE
缺少video list

### ISSUE THREAD

**Issue by georgefs** [livingbio/elta_spider#6]

**Comment by yun1113** [comment]
| name | video_name | fifa_url |
| --- | --- | --- |
| GroupA_Brazil_Croatia |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186456/live-blog.html |
| GroupA_Mexico_Cameroon |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186492/live-blog.html |
| GroupB_Spain_Netherlands |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186510/live-blog.html |
| GroupB_Chile_Australia |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186473/live-blog.html |
| GroupC_Colombia_Greece |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186471/live-blog.html |
| GroupD_England_Italy |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186513/live-blog.html |
| GroupC_IvoryCoast_Japan |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186507/live-blog.html |
| GroupE_Switzerland_Ecuador |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186494/live-blog.html |
| GroupF_Argentina_BosniaAndHerzegovina |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186477/live-blog.html |
| GroupG_Germany_Portugal |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186475/live-blog.html |
| GroupF_Iran_Nigeria |  | http://www.fifa.com/worldcup/archive/brazil2014/matches/index.html |
| GroupG_Ghana_USA |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186512/live-blog.html |
| GroupH_Belgium_Algeria |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186479/live-blog.html |
| GroupA_Brazil_Mexico |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186509/live-blog.html |
| GroupH_Russia_KoreaRepublic |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186499/live-blog.html |
| GroupB_Australia_Netherlands |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186478/live-blog.html |
| GroupB_Spain_Chile |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186498/live-blog.html |
| GroupA_Cameroon_Croatia |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186453/live-blog.html |
| GroupC_Colombia_IvoryCoast |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186468/live-blog.html |
| GroupD_Uruguay_England |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186486/live-blog.html |
| GroupC_Japan_Greece |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186454/live-blog.html |
| GroupD_Italy_CostaRica |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186500/live-blog.html |
| GroupE_Honduras_Ecuador |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186463/live-blog.html |
| GroupF_Argentina_Iran |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186466/live-blog.html |
| GroupF_Nigeria_BosniaAndHerzegovina |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186511/live-blog.html |
| GroupH_Belgium_Russia |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186481/live-blog.html |
| GroupH_KoreaRepuplic_Algeria |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186495/live-blog.html |
| GroupG_USA_Portugal |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186483/live-blog.html |
| GroupA_Croatia_Mexico |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186452/live-blog.html |
| GroupA_Cameroon_Brazil |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186472/live-blog.html |
| GroupB_Netherlands_Chile |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186470/live-blog.html |
| GroupB_Australia_Spain |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186467/live-blog.html |
| GroupE_Ecuador_France |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186515/live-blog.html |
| GroupG_USA_Germany |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186469/live-blog.html |
| GroupH_KoreaRepuplic_Belgium |  | http://www.fifa.com/worldcup/matches/round=255931/match=300186480/live-blog.html |
| RoundOf16_Brazil_Chile |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186487/live-blog.html |
| RoundOf16_Colombia_Uruguay |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186491/live-blog.html |
| RoundOf16_Netherlands_Mexico |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186508/live-blog.html |
| RoundOf16_CostaRica_Greece |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186459/live-blog.html |
| RoundOf16_France_Nigeria |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186462/live-blog.html |
| RoundOf16_Germany_Algeria |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186460/live-blog.html |
| RoundOf16_Argentina_Switzerland |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186503/live-blog.html |
| RoundOf16_Belgium_USA |  | http://www.fifa.com/worldcup/matches/round=255951/match=300186497/live-blog.html |
| QuarterFinals_France_Germany |  | http://www.fifa.com/worldcup/matches/round=255953/match=300186485/live-blog.html |
| QuarterFinals_Brazil_Colombia |  | http://www.fifa.com/worldcup/matches/round=255953/match=300186461/live-blog.html |
| QuarterFinals_Argentina_Belgium |  | http://www.fifa.com/worldcup/matches/round=255953/match=300186504/live-blog.html |
| QuarterFinals_Netherlands_CostaRica |  | http://www.fifa.com/worldcup/matches/round=255953/match=300186488/live-blog.html |
| SemiFinals_Brazil_Germany |  | http://www.fifa.com/worldcup/matches/round=255955/match=300186474/live-blog.html |
| SemiFinals_Netherlands_Argentina |  | http://www.fifa.com/worldcup/matches/round=255955/match=300186490/live-blog.html |
